# Generated by Django 2.2.6 on 2019-10-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalinfo',
            options={'verbose_name_plural': 'General Information'},
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='email',
            field=models.EmailField(default='contact@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
