# Generated by Django 2.2.6 on 2019-10-08 17:12

from django.db import migrations


def add_initial_data(apps, schema_editor):
    GeneralInfo = apps.get_model('config', 'GeneralInfo')
    info = GeneralInfo(
        name='Shrimp Heaven',
        phone='202-555-0116',
        email='hello@example.com',
        logo='info/logo.png'
    )
    info.save()

class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20191007_1629'),
    ]

    operations = [
        migrations.RunPython(add_initial_data)
    ]
