# Generated by Django 2.2.6 on 2019-10-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
