# Generated by Django 2.2.6 on 2019-10-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20191004_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.ManyToManyField(limit_choices_to={'active': True}, to='menu.MenuTag'),
        ),
        migrations.AddField(
            model_name='menutag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menutag',
            name='icon',
            field=models.CharField(help_text='<a href="https://fontawesome.com/icons?d=gallery&m=free" target="_blank">Check available icons</a>', max_length=50),
        ),
    ]
