# Generated by Django 2.2.6 on 2019-10-04 23:18

from django.db import migrations

def add_initial_data(apps, schema_editor):
    MenuCategory = apps.get_model('menu', 'MenuCategory')
    MenuTag = apps.get_model('menu', 'MenuTag')
    MenuItem = apps.get_model('menu', 'MenuItem')
    
    MenuCategory.objects.bulk_create([
        MenuCategory(
            name='Starters',
            order=1,
            image='categories/starters.png',
            active=True,
        ),
        MenuCategory(
            name='Shirmp Addiction',
            order=2,
            image='categories/shrimp-addiction.png',
            active=True,
        ),
         MenuCategory(
            name='Drinks',
            order=3,
            image='categories/drinks.png',
            active=True,
        ),
        MenuCategory(
            name='Desserts',
            order=4,
            image='categories/desserts.png',
            active=False,
        ),
    ])

    MenuTag.objects.bulk_create([
        MenuTag(
            name='Spicey',
            icon='fas fa-pepper-hot'
        ),
        MenuTag(
            name='Shareable',
            icon='fas fa-users'
        ),
        MenuTag(
            name='Healthy',
            icon='fas fa-heart'
        )
    ])

    starter_category = MenuCategory.objects.get(order=1)
    shareable_tag = MenuTag.objects.get(name='Shareable')

    shrimp_nachos = MenuItem(
        name='Shrimp Nachos',
        order=1,
        image='items/shrimp-nachos.jpg',
        active=True,
        description='Tortilla bathed with a mixture of Monterey cheeses, jack, mozzarella and cheddar, pico de gallo and fresh jalapenos and shrimp',
        price=24,
        category=starter_category,
        
    )
    shrimp_nachos.save()
    shrimp_nachos.tags.set([shareable_tag])

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20191004_1617'),
    ]

    operations = [
        migrations.RunPython(add_initial_data)
    ]
