# Generated by Django 2.2.6 on 2019-10-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20191004_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutag',
            name='color',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
